### PR TITLE
Local docker

### PR DESCRIPTION
**Pull request by cornelv**

### CODE REVIEW

**Comment by CarliJoy** [comment]
Thanks for the PR.
I will test it within the weekend. But give me some time, I have no experience with docker so far.
I think if we add a docker container we also should add a test for the creation etc in travis. 
If you know how to do that already, feel free to edit the travis.yml file.

**Comment by CarliJoy** [comment]
PS: You PR is on your own repro but not on the master repro.

**Comment by cornelv** [comment]
Hi @CarliJoy  I made the PR on my fork because I didn't know if the docker route for local development is ok for you, I will change it. Unfortunately I don't have much experience with travis, so I am not sure what updates we need to make. But I'm happy to get involved

**Comment by cornelv** [comment]
I created the PR here:  https://github.com/CarliJoy/django-pint/pull/28   I will close this one

**Pull request closed without merging**
